# Generated by Django 2.0.1 on 2018-01-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_Klass_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('slot_length', models.PositiveSmallIntegerField()),
                ('num_slots', models.PositiveSmallIntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass')),
            ],
            options={
                'verbose_name': 'Alternate Class Schedule',
                'verbose_name_plural': 'Alternate Class Schedules',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('not_available', models.BooleanField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classlists.Klass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classlists.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Standard_Day_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('slot_length', models.PositiveSmallIntegerField()),
                ('num_slots', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Standard Schedule',
                'verbose_name_plural': 'Standard Schedules',
            },
        ),
    ]
