# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160912_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='klassscheduledetails',
            options={'verbose_name': 'Class Schedule', 'verbose_name_plural': 'Class Schedules'},
        ),
        migrations.AlterModelOptions(
            name='schoolscheduledetails',
            options={'verbose_name': 'School Schedule', 'verbose_name_plural': 'School Schedule'},
        ),
    ]
