# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_slot_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolscheduledetails',
            name='name',
            field=models.CharField(default='qvic', max_length=20),
            preserve_default=False,
        ),
    ]
